### ISSUE TITLE
forgetpassword has issues

### ISSUE THREAD

**Issue by i928** [phalcon/vokuro#10]
trace with forgetpassword 
```
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'users.username' in 'field list'
#0 [internal function]: PDOStatement->execute()
#1 [internal function]: Phalcon\Db\Adapter\Pdo->executePrepared(Object(PDOStatement), Array, Array)
#2 [internal function]: Phalcon\Db\Adapter\Pdo->query('SELECT `users`....', Array, Array)
#3 [internal function]: Phalcon\Mvc\Model\Query->_executeSelect(Array, Array, Array)
#4 [internal function]: Phalcon\Mvc\Model\Query->execute(Array, Array)
#5 [internal function]: Phalcon\Mvc\Model::findFirst(Array)
#6 C:\inetpub\wwwroot\ccn\phalcon\Phalcon\vokuro\app\controllers\SessionController.php(117): Phalcon\Mvc\Model::__callStatic('findFirstByEmai...', Array)
#7 C:\inetpub\wwwroot\ccn\phalcon\Phalcon\vokuro\app\controllers\SessionController.php(117): Vokuro\Models\Users::findFirstByEmail('chiiwenl@yahoo....')
#8 [internal function]: Vokuro\Controllers\SessionController->forgotPasswordAction()
#9 [internal function]: Phalcon\Dispatcher->dispatch()
#10 C:\inetpub\wwwroot\ccn\phalcon\Phalcon\vokuro\public\index.php(33): Phalcon\Mvc\Application->handle()
#11 {main}
```

**Comment by sergeysviridenko** [comment]
I couldn't reproduce this issue. It works fine for me.

Phalcon Version: 3.2.1
