### ISSUE TITLE
after signup error

### ISSUE THREAD

**Issue by raxan** [phalcon/vokuro#22]
Hi

how to fix this issue:

No credentials were provided. The SDK attempts to retrieve Instance Profile credentials from the EC2 Instance Metadata Service, but doing this requires the "default_cache_config" option to be set in the config.inc.php file or constructor. In order to cache the retrieved credentials.
```
#0 /Applications/MAMP/htdocs/phalcon/vokuro/vendor/amazonwebservices/aws-sdk-for-php/services/ses.class.php(77): CFRuntime->__construct(Array)
#1 /Applications/MAMP/htdocs/phalcon/vokuro/app/library/Mail/Mail.php(33): AmazonSES->__construct(Array)
#2 /Applications/MAMP/htdocs/phalcon/vokuro/app/library/Mail/Mail.php(113): Vokuro\Mail\Mail->amazonSESSend('Message-ID: <84...')
#3 /Applications/MAMP/htdocs/phalcon/vokuro/app/models/EmailConfirmations.php(76): Vokuro\Mail\Mail->send(Array, 'Please confirm ...', 'confirmation', Array)
#4 [internal function]: Vokuro\Models\EmailConfirmations->afterCreate()
#5 [internal function]: Phalcon\Mvc\Model->fireEvent('afterCreate')
#6 [internal function]: Phalcon\Mvc\Model->_postSave(true, false)
#7 /Applications/MAMP/htdocs/phalcon/vokuro/app/models/Users.php(111): Phalcon\Mvc\Model->save()
#8 [internal function]: Vokuro\Models\Users->afterSave()
#9 [internal function]: Phalcon\Mvc\Model->fireEvent('afterSave')
#10 [internal function]: Phalcon\Mvc\Model->_postSave(true, false)
#11 /Applications/MAMP/htdocs/phalcon/vokuro/app/controllers/SessionController.php(50): Phalcon\Mvc\Model->save()
#12 [internal function]: Vokuro\Controllers\SessionController->signupAction()
#13 [internal function]: Phalcon\Dispatcher->dispatch()
#14 /Applications/MAMP/htdocs/phalcon/vokuro/public/index.php(33): Phalcon\Mvc\Application->handle()
#15 {main}
```

**Comment by sergeysviridenko** [comment]
It looks like you didn't fill settings in `config.php`. I have had the same problem when I've tried to create a new account without mail settings. I've used `smtp.gmail.com`.
